In [1]:
!pip install selenium

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: selenium in c:\users\navee\appdata\roaming\python\python39\site-packages (4.7.2)
Requirement already satisfied: urllib3[socks]~=1.26 in c:\programdata\anaconda3\lib\site-packages (from selenium) (1.26.9)
Requirement already satisfied: trio~=0.17 in c:\users\navee\appdata\roaming\python\python39\site-packages (from selenium) (0.22.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\navee\appdata\roaming\python\python39\site-packages (from selenium) (0.9.2)
Requirement already satisfied: certifi>=2021.10.8 in c:\programdata\anaconda3\lib\site-packages (from selenium) (2021.10.8)
Requirement already satisfied: sniffio in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: sortedcontainers in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\navee\appdata\roaming\python\python39\site-packages (from trio~=0.17->selenium) (1.0.4)
Requirement already satisfied: idna in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: async-generator>=1.9 in c:\users\navee\appdata\roaming\python\python39\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: cffi>=1.14 in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.0)
Requirement already satisfied: outcome in c:\users\navee\appdata\roaming\python\python39\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: attrs>=19.2.0 in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: wsproto>=0.14 in c:\users\navee\appdata\roaming\python\python39\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\programdata\anaconda3\lib\site-packages (from urllib3[socks]~=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\navee\appdata\roaming\python\python39\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [18]:
import selenium
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from selenium.common.exceptions import ElementClickInterceptedException
from selenium.webdriver.common.by import  By
import time
import requests

# Q1. Scrape the details of most viewed videos on YouTube from Wikipedia.

In [137]:
# Connecting to the driver
driver = webdriver.Chrome(r"C:\Users\navee\Downloads\chromedriver_win32\chromedriver.exe")

In [138]:
# Opening web Page
driver.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")

In [139]:
# Scraping Rank

rank = []

rk = driver.find_elements(By.XPATH,'//*[@id="mw-content-text"]/div[1]/table[2]/tbody/tr/td[1]')
for i in rk:
    rank.append(i.text)

# Scraping Name

Name = []

nam = driver.find_elements(By.XPATH,'//*[@id="mw-content-text"]/div[1]/table[2]/tbody/tr/td[2]')
for i in nam:
    Name.append(i.text)

# Scraping Artist

Artist = []

art = driver.find_elements(By.XPATH,'//*[@id="mw-content-text"]/div[1]/table[2]/tbody/tr/td[3]')
for i in art:
    Artist.append(i.text)
    
# Scrapping Upload Date

date = []

dt = driver.find_elements(By.XPATH,'//*[@id="mw-content-text"]/div[1]/table[2]/tbody/tr/td[5]')
for i in dt:
    date.append(i.text)

# Scrapping views

views = []

vw = driver.find_elements(By.XPATH,'//*[@id="mw-content-text"]/div[1]/table[2]/tbody/tr/td[4]')
for i in vw:
    views.append(i.text)

In [ ]:
# Removing numerical data from Name

import re

name3 = []
for i in range(len(Name)):
    if i==len(Name)-31:
         break
    else:
        name2 = re.sub(r'\[[0-9]*\]', '', Name[i])
    name3.append(name2)

In [144]:
# Creating DataFrame

yt = pd.DataFrame({"Rank":rank, "Name":name3,"Artist":Artist,"Upload Date":date,"Views":views})
yt

,Rank,Name,Artist,Upload Date,Views
0,1.,"""Baby Shark Dance""",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",12.13
1,2.,"""Despacito""",Luis Fonsi,"January 12, 2017",8.07
2,3.,"""Johny Johny Yes Papa""",LooLoo Kids,"October 8, 2016",6.59
3,4.,"""Bath Song""",Cocomelon – Nursery Rhymes,"May 2, 2018",5.96
4,5.,"""Shape of You""",Ed Sheeran,"January 30, 2017",5.89
5,6.,"""See You Again""",Wiz Khalifa,"April 6, 2015",5.76
6,7.,"""Phonics Song with Two Words""",ChuChu TV,"March 6, 2014",5.12
7,8.,"""Wheels on the Bus""",Cocomelon – Nursery Rhymes,"May 24, 2018",4.84
8,9.,"""Uptown Funk""",Mark Ronson,"November 19, 2014",4.80
9,10.,"""Learning Colors – Colorful Eggs on a Farm""",Miroshka TV,"February 27, 2018",4.79
10,11.,"""Gangnam Style""",Psy,"July 15, 2012",4.66
11,12.,"""Masha and the Bear – Recipe for Disaster""",Get Movies,"January 31, 2012",4.52
12,13.,"""Dame Tu Cosita""",El Chombo,"April 5, 2018",4.21
13,14.,"""Sugar""",Maroon 5,"January 14, 2015",3.81
14,15.,"""Roar""",Katy Perry,"September 5, 2013",3.72
15,16.,"""Counting Stars""",OneRepublic,"May 31, 2013",3.71
16,17.,"""Axel F""",Crazy Frog,"June 16, 2009",3.71
17,18.,"""Sorry""",Justin Bieber,"October 22, 2015",3.62
18,19.,"""Thinking Out Loud""",Ed Sheeran,"October 7, 2014",3.54
19,20.,"""Baa Baa Black Sheep""",Cocomelon – Nursery Rhymes,"June 25, 2018",3.48
20,21.,"""Waka Waka (This Time for Africa)""",Shakira,"June 4, 2010",3.44
21,22.,"""Dark Horse""",Katy Perry,"February 20, 2014",3.43
22,23.,"""Faded""",Alan Walker,"December 3, 2015",3.39
23,24.,"""Let Her Go""",Passenger,"July 25, 2012",3.37
24,25.,"""Girls Like You""",Maroon 5,"May 31, 2018",3.36
25,26.,"""Perfect""",Ed Sheeran,"November 9, 2017",3.35
26,27.,"""Bailando""",Enrique Iglesias,"April 11, 2014",3.32
27,28.,"""Lean On""",Major Lazer,"March 22, 2015",3.32
28,29.,"""Humpty the train on a fruits ride""",Kiddiestv Hindi – Nursery Rhymes & Kids Songs,"January 26, 2018",3.29
29,30.,"""Lakdi Ki Kathi""",Jingle Toons,"June 14, 2018",3.26

# Q2.  Scrape the details team India’s international fixtures from bcci.tv.

In [215]:
# Connecting to the driver
driver = webdriver.Chrome(r"C:\Users\navee\Downloads\chromedriver_win32\chromedriver.exe")

In [216]:
# Opening web Page
driver.get("http://www.bcci.tv/")

try:
    search1 = driver.find_element(By.XPATH,'//*[@id="navigation"]/ul[1]/li[2]/a')
    search1.click()
except NoSuchElementException:
    search2 = driver.find_element(By.XPATH,'//button[@data-target="#navigation"]')
    search2.click()
except NoSuchElementException:
    search3 = driver.find_element(By.XPATH,'//*[@id="navigation"]/ul[1]/li[2]/a')
    search3.click()
    time.sleep(3)


for _ in range(0,20):
    driver.execute_script("window.scrollBy(0,50)")
search4 = driver.find_element(By.XPATH,'//button[@ng-click="viewMoreMatches()"]')
search4.click()

In [217]:
# Scraping Title

title = []

tit = driver.find_elements(By.XPATH,'//span[@class="matchOrderText ng-binding ng-scope"]')
for i in tit:
    title.append(i.text)


# Scraping series

series = []
ser = driver.find_elements(By.XPATH,'//span[@class="ng-binding"]')
for i in ser:
    series.append(i.text)
    

# scraping place
place = []
pl = driver.find_elements(By.XPATH,'//div[@class="fix-place ng-binding ng-scope"]')
for i in pl:
    place.append(i.text)


place3 = []
for i in range(len(place)):
    if i==len(place)-17:
        break
    else:
        place2 = place[i].split(' ')[3:]
    place3.append(place2)

place4 = [' '.join(i) for i in place3]
place4
    
# scraping date
date = []
dt = driver.find_elements(By.XPATH,'//h5[@class="ng-binding"]')
for i in dt:
    date.append(i.text)

    
# scraping time
time = []
tt = driver.find_elements(By.XPATH,'//h5[@class="text-right ng-binding"]')
for i in tt:
    time.append(i.text)

In [219]:
# Creating DataFrame

india_fixtures = pd.DataFrame({"Match Title":title,"Series":series,"Place":place4,"Date":date,"Time":time}) 
india_fixtures

,Match Title,Series,Place,Date,Time
0,1st T20I -,WOMENS T20I TRI-SERIES IN SOUTH AFRICA 2023,"Buffalo Park, East London",19 JAN 2023,10:30 PM IST
1,2nd ODI -,NEW ZEALAND TOUR OF INDIA ODI SERIES 2022-23,Shaheed Veer Narayan Singh International Crick...,21 JAN 2023,1:30 PM IST
2,2nd T20I -,WOMENS T20I TRI-SERIES IN SOUTH AFRICA 2023,"Buffalo Park, East London",23 JAN 2023,10:30 PM IST
3,3rd ODI -,NEW ZEALAND TOUR OF INDIA ODI SERIES 2022-23,"Holkar Cricket Stadium, Indore",24 JAN 2023,1:30 PM IST
4,1st T20I -,NEW ZEALAND TOUR OF INDIA T20 SERIES 2022-23,"JSCA International Stadium Complex, Ranchi",27 JAN 2023,7:00 PM IST
5,3rd T20I -,WOMENS T20I TRI-SERIES IN SOUTH AFRICA 2023,"Buffalo Park, East London",28 JAN 2023,10:30 PM IST
6,2nd T20I -,NEW ZEALAND TOUR OF INDIA T20 SERIES 2022-23,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,29 JAN 2023,7:00 PM IST
7,4th T20I -,WOMENS T20I TRI-SERIES IN SOUTH AFRICA 2023,"Buffalo Park, East London",30 JAN 2023,6:30 PM IST
8,3rd T20I -,NEW ZEALAND TOUR OF INDIA T20 SERIES 2022-23,"Narendra Modi Stadium, Ahmedabad",1 FEB 2023,7:00 PM IST
9,1st Test -,AUSTRALIA TOUR OF INDIA TEST SERIES 2022-23,"Vidarbha Cricket Association Stadium, Nagpur",9 FEB 2023,9:30 AM IST
10,2nd Test -,AUSTRALIA TOUR OF INDIA TEST SERIES 2022-23,"Arun Jaitley Stadium, Delhi",17 FEB 2023,9:30 AM IST
11,3rd Test -,AUSTRALIA TOUR OF INDIA TEST SERIES 2022-23,"Himachal Pradesh Cricket Association Stadium, ...",1 MAR 2023,9:30 AM IST
12,4th Test -,AUSTRALIA TOUR OF INDIA TEST SERIES 2022-23,"Narendra Modi Stadium, Ahmedabad",9 MAR 2023,9:30 AM IST
13,1st ODI -,AUSTRALIA TOUR OF INDIA ODI SERIES 2022-23,"Wankhede Stadium, Mumbai",17 MAR 2023,1:30 PM IST
14,2nd ODI -,AUSTRALIA TOUR OF INDIA ODI SERIES 2022-23,Dr YS Rajasekhara Reddy ACA-VDCA Cricket Stadi...,19 MAR 2023,1:30 PM IST
15,3rd ODI -,AUSTRALIA TOUR OF INDIA ODI SERIES 2022-23,"MA Chidambaram Stadium, Chennai",22 MAR 2023,1:30 PM IST

# Q3. Scrape the details of selenium exception from guru99.com.

In [246]:
# Connecting to the driver
driver = webdriver.Chrome(r"C:\Users\navee\Downloads\chromedriver_win32\chromedriver.exe")

In [247]:
# Opening web Page
driver.get("http://www.guru99.com/")

search1 = driver.find_element(By.XPATH,'//*[@id="java_technologies"]/li[3]/a')
search1.click()

try:
    search1 = driver.find_element(By.XPATH,'//a[@title="Selenium Exception Handling (Common Exceptions List)"]')
    search1.click()
except NoSuchElementException:
    search1 = driver.find_element(By.XPATH,'//a[@title="Selenium Exception Handling (Common Exceptions List)"]')
    search1.click()

In [ ]:
# scraping Name
sel = []
nm = driver.find_elements(By.XPATH,'//*[@id="post-1953"]/div/div/p')
for i in nm[0:41]:
    sel.append(i.text)
sel

In [ ]:
name_sel = []
for i in range(len(sel)):
    if i==len(sel)-48:
        break
    else:
        name_ = sel[i].split(':')[:1]
    name_sel.append(name_)

In [ ]:
description = []
for i in range(len(names)):
    if i==len(names)-48:
        break
    else:
        des = names[i].split(':')[1:]
    description.append(des)

In [259]:
# Creating DataFrame


selenium_exception = pd.DataFrame({"Name":name_sel,"Description":description})
selenium_exception

,Name,Description
0,[1. ElementNotVisibleException],[ This type of Selenium exception occurs when ...
1,[2. ElementNotSelectableException],[ This Selenium exception occurs when an eleme...
2,[3. NoSuchElementException],[ This Exception occurs if an element could no...
3,[4. NoSuchFrameException],[ This Exception occurs if the frame target to...
4,[5. NoAlertPresentException],[ This Exception occurs when you switch to no ...
5,[6. NoSuchWindowException],[ This Exception occurs if the window target t...
6,[7. StaleElementReferenceException],[ This Selenium exception occurs happens when ...
7,[8. SessionNotFoundException],[ The WebDriver is acting after you quit the b...
8,[9. TimeoutException],[ Thrown when there is not enough time for a c...
9,[10. WebDriverException],[ This Exception takes place when the WebDrive...
10,[11. ConnectionClosedException],[ This type of Exception takes place when ther...
11,[12. ElementClickInterceptedException],[ The command may not be completed as the elem...
12,[13. ElementNotInteractableException],[ This Selenium exception is thrown when any e...
13,[14. ErrorInResponseException],[ This happens while interacting with the Fire...
14,[15. ErrorHandler.UnknownServerException],[ Exception is used as a placeholder in case i...
15,[16. ImeActivationFailedException],[ This expectation will occur when IME engine ...
16,[17. ImeNotAvailableException],[ It takes place when IME support is unavailab...
17,[18. InsecureCertificateException],[ Navigation made the user agent to hit a cert...
18,[19. InvalidArgumentException],[ It occurs when an argument does not belong t...
19,[20. InvalidCookieDomainException],[ This happens when you try to add a cookie un...
20,[21. InvalidCoordinatesException],[ This type of Exception matches an interactin...
21,[22. InvalidElementStateException],[ It occurs when command can’t be finished whe...
22,[23. InvalidSessionIdException],[ This Exception took place when the given ses...
23,[24. InvalidSwitchToTargetException],[ This occurs when the frame or window target ...
24,[25. JavascriptException],[ This issue occurs while executing JavaScript...
25,[26. JsonException],[ It occurs when you afford to get the session...
26,[27. NoSuchAttributeException],[ This kind of Exception occurs when the attri...
27,[28. MoveTargetOutOfBoundsException],[ It takes place if the target provided to the...
28,[29. NoSuchContextException],[ ContextAware does mobile device testing.]
29,[30. NoSuchCookieException],[ This Exception occurs when no cookie matchin...
30,[31. NotFoundException],[ This Exception is a subclass of WebDriverExc...
31,[32. RemoteDriverServerException],[ This Selenium exception is thrown when the s...
32,[33. ScreenshotException],[ It is not possible to capture a screen.]
33,[34. SessionNotCreatedException],[ It happens when a new session could not be s...
34,[35. UnableToSetCookieException],[ This occurs if a driver is unable to set a c...
35,[36. UnexpectedTagNameException],[ Happens if a support class did not get a web...
36,[37. UnhandledAlertException],[ This expectation occurs when there is an ale...
37,[38. UnexpectedAlertPresentException],[ It occurs when there is the appearance of an...
38,[39. UnknownMethodException],[ This Exception happens when the requested co...
39,[40. UnreachableBrowserException],[ This Exception occurs only when the browser ...
40,[41. UnsupportedCommandException],[ This occurs when remote WebDriver doesn’t se...

# Q4. Scrape the details of State-wise GDP of India from statisticstime.com

In [411]:
# Connecting to the driver
driver = webdriver.Chrome(r"C:\Users\navee\Downloads\chromedriver_win32\chromedriver.exe")
time.sleep(5)

# Opening web Page

driver.get("http://statisticstimes.com/")

try:
    search1 = driver.find_element(By.XPATH,'//*[@id="top"]/div[2]/div[2]/button')
    search1.click()
except InvalidSelectorException:
    search1 = driver.find_element(By.XPATH,'//*[@id="top"]/div[2]/div[2]/button')
    search1.click()
except ElementNotInteractableException:
    search1 = driver.find_element(By.XPATH,'//*[@id="top"]/div[2]/div[2]/button')
    search1.click()

try:
    search2 = driver.find_element(By.XPATH,'//*[@id="top"]/div[2]/div[2]/div/a[3]')
    search2.click()
except ElementNotInteractableException:
    search2 = driver.find_element(By.XPATH,'//*[@id="top"]/div[2]/div[2]/div/a[3]')
    search2.click()
    time.sleep(5)

# Ignoring Advertisement

driver.get("https://www.statisticstimes.com/economy/india-statistics.php")
search3 = driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
search3.click()
time.sleep(10)


rank_gdp = []
st_gdp = []
GSDP1 = []
GSDP2 = []
share = []
bill = []

rk = driver.find_elements(By.XPATH,'//*[@id="table_id"]/tbody/tr/td[1]')
for i in rk:
    rank_gdp.append(i.text)


st = driver.find_elements(By.XPATH,'//*[@id="table_id"]/tbody/tr/td[2]')
for i in st:
    st_gdp.append(i.text)


gs1 = driver.find_elements(By.XPATH,'//*[@id="table_id"]/tbody/tr/td[4]')
for i in gs1:
    GSDP1.append(i.text)


gs2 = driver.find_elements(By.XPATH,'//*[@id="table_id"]/tbody/tr/td[3]')
for i in gs2:
    GSDP2.append(i.text)


sh = driver.find_elements(By.XPATH,'//*[@id="table_id"]/tbody/tr/td[5]')
for i in sh:
    share.append(i.text)


bl = driver.find_elements(By.XPATH,'//*[@id="table_id"]/tbody/tr/td[6]')
for i in bl:
    bill.append(i.text)

In [412]:
# Creating DataFrame

GDP = pd.DataFrame({"Rank":rank_gdp,"State":st_gdp,"GSDP(18-19)":GSDP1," GSDP(19-20)":GSDP2,"Share(18-19)":share,
                    "GDP($ Billion)":bill})
GDP

,Rank,State,GSDP(18-19),GSDP(19-20),Share(18-19),GDP($ Billion)
0,1,Maharashtra,"2,632,792",-,13.94%,399.921
1,2,Tamil Nadu,"1,630,208","1,845,853",8.63%,247.629
2,3,Uttar Pradesh,"1,584,764","1,687,818",8.39%,240.726
3,4,Gujarat,"1,502,899",-,7.96%,228.290
4,5,Karnataka,"1,493,127","1,631,977",7.91%,226.806
5,6,West Bengal,"1,089,898","1,253,832",5.77%,165.556
6,7,Rajasthan,"942,586","1,020,989",4.99%,143.179
7,8,Andhra Pradesh,"862,957","972,782",4.57%,131.083
8,9,Telangana,"861,031","969,604",4.56%,130.791
9,10,Madhya Pradesh,"809,592","906,672",4.29%,122.977
10,11,Kerala,"781,653",-,4.14%,118.733
11,12,Delhi,"774,870","856,112",4.10%,117.703
12,13,Haryana,"734,163","831,610",3.89%,111.519
13,14,Bihar,"530,363","611,804",2.81%,80.562
14,15,Punjab,"526,376","574,760",2.79%,79.957
15,16,Odisha,"487,805","521,275",2.58%,74.098
16,17,Assam,"315,881",-,1.67%,47.982
17,18,Chhattisgarh,"304,063","329,180",1.61%,46.187
18,19,Jharkhand,"297,204","328,598",1.57%,45.145
19,20,Uttarakhand,"245,895",-,1.30%,37.351
20,21,Jammu & Kashmir,"155,956",-,0.83%,23.690
21,22,Himachal Pradesh,"153,845","165,472",0.81%,23.369
22,23,Goa,"73,170","80,449",0.39%,11.115
23,24,Tripura,"49,845","55,984",0.26%,7.571
24,25,Chandigarh,"42,114",-,0.22%,6.397
25,26,Puducherry,"34,433","38,253",0.18%,5.230
26,27,Meghalaya,"33,481","36,572",0.18%,5.086
27,28,Sikkim,"28,723","32,496",0.15%,4.363
28,29,Manipur,"27,870","31,790",0.15%,4.233
29,30,Nagaland,"27,283",-,0.14%,4.144
30,31,Arunachal Pradesh,"24,603",-,0.13%,3.737
31,32,Mizoram,"22,287","26,503",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

# Q5. Scrape the details of trending repositories on Github.com

In [37]:
# Connecting to the driver
driver = webdriver.Chrome(r"C:\Users\navee\Downloads\chromedriver_win32\chromedriver.exe")
time.sleep(3)

# Opening web Page
driver.get("https://github.com/")
time.sleep(5)

# Navigating through trending repository
search1 = driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/button')
search1.click()
    
search1 = driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/ul[3]/li[3]/a')
search1.click()
time.sleep(3)


# Scraping Repository URL

gt_url = []

url = driver.find_elements(By.XPATH,'/html/body/div[1]/div[4]/main/div[3]/div/div[2]/article/h1/a')
for i in url:
    gt_url.append(i.get_attribute("href"))


# Scraping Name from Title

title = []
for i in range(len(gt_url)):
    if i==len(gt_url)-26:
        break
    else:
        tit = gt_url[i].split('/github.com/')[1:]
    title.append(tit)

    
# Scraping Description

des = []

for url in gt_url[0:25]:
    driver.get(url)
    time.sleep(2)
    
    try:
        desc = driver.find_element(By.XPATH,'//*[@id="repo-content-pjax-container"]/div/div/div[3]/div[2]/div/div[1]/div')
        des.append(desc.text)
    except NoSuchElementException:
        des.append('-')

description = []
for i in range(len(des)):
    if i==len(des)-26:
        break
    else:
        des1 = des[i].split('\n')[1:2]
    description.append(des1)

    
# Scraping Contributors

cont = []

for url in gt_url[0:25]:
    driver.get(url)
    time.sleep(3)
    
    try:
        con = driver.find_element(By.XPATH,"//*[contains(text(),'    Contributors ')]")
        cont.append(con.text)
    except NoSuchElementException:
        cont.append('-')

# Scraping Language

lang = []

for url in gt_url[0:25]:
    driver.get(url)
    time.sleep(3)
    
    try:
        lan = driver.find_elements(By.XPATH,'//ul[@class="list-style-none"]')
        for i in lan[-1:]:
            la = i.text
            lang.append(la)
    except NoSuchElementException:
        lang.append('-')

lang2 = []

for i in range(len(lang)):
    if i == len(lang)-26:
        break
    else:
        lan2 = lang[i].split('\n')
    lang2.append(lan2)

In [39]:
# Creating DataFrame

Trending_repository = pd.DataFrame({"Repository Title":title,"Repository Description": description,
                                    "Contributors Count":cont,"Language Used":lang2})
Trending_repository

,Repository Title,Repository Description,Contributors Count,Language Used
0,[brycedrennan/imaginAIry],[AI imagined images. Pythonic generation of st...,Contributors 9,"[Python, 98.9%, Other, 1.1%]"
1,[trekhleb/javascript-algorithms],[📝 Algorithms and data structures implemented ...,Contributors 197,"[JavaScript, 100.0%]"
2,[LazyVim/LazyVim],[Neovim config for the lazy],Contributors 15,"[Lua, 100.0%]"
3,[bellingcat/octosuite],[Advanced Github OSINT Framework],Contributors 3,"[Python, 99.8%, Dockerfile, 0.2%]"
4,[cloudflare/wildebeest],[Wildebeest is an ActivityPub and Mastodon-com...,Contributors 8,"[TypeScript, 97.5%, JavaScript, 1.3%, Other, 1..."
5,[timothybrooks/instruct-pix2pix],"[No description, website, or topics provided.]",Contributors 11,"[Python, 99.3%, Shell, 0.7%]"
6,[1c7/chinese-independent-developer],[👩🏿‍💻👨🏾‍💻👩🏼‍💻👨🏽‍💻👩🏻‍💻中国独立开发者项目列表 -- 分享大家都在做什么],Contributors 105,[]
7,[Developer-Y/cs-video-courses],[List of Computer Science courses with video l...,Contributors 81,[]
8,[hyprwm/Hyprland],[Hyprland is a dynamic tiling Wayland composit...,Contributors 86,"[C++, 96.5%, Nix, 1.6%, Makefile, 0.8%, Meson,..."
9,[google-research/tuning_playbook],[A playbook for systematically maximizing the ...,Contributors 2,[]
10,[google/comprehensive-rust],[This is the Rust course used by the Android t...,Contributors 47,"[Rust, 71.1%, JavaScript, 15.4%, Shell, 5.6%, ..."
11,[shadcn/ui],[Beautifully designed components built with Ra...,-,"[TypeScript, 95.8%, JavaScript, 3.1%, Other, 1..."
12,[DaviMarta/Automatiza-o],"[No description, website, or topics provided.]",-,"[Jupyter Notebook, 66.4%, Python, 33.6%]"
13,[mage-ai/mage-ai],"[🧙 The modern replacement for Airflow. Build, ...",Contributors 21,"[Python, 61.4%, TypeScript, 33.5%, HTML, 4.0%,..."
14,[databricks-academy/data-engineer-learning-path],"[No description, website, or topics provided.]",-,"[Python, 100.0%]"
15,[pynecone-io/pynecone],[🕸 Web apps in pure Python 🐍],Contributors 20,"[Python, 90.4%, JavaScript, 9.6%]"
16,[jerryjliu/gpt_index],[GPT Index is a project consisting of a set of...,Contributors 27,"[Python, 96.9%, Jupyter Notebook, 3.1%]"
17,[dair-ai/AI-Product-Index],[A curated index to track AI-powered products.],Contributors 7,[]
18,[resendlabs/react-email],[💌 Build and send emails using React],Contributors 28,"[TypeScript, 95.4%, JavaScript, 4.6%]"
19,[nuxt/nuxt],[Nuxt is an intuitive and extendable way to cr...,Contributors 365,"[TypeScript, 97.4%, JavaScript, 1.7%, Other, 0..."
20,[f/awesome-chatgpt-prompts],[This repo includes ChatGPT prompt curation to...,Contributors 54,"[HTML, 100.0%]"
21,[ossu/computer-science],[🎓 Path to a free self-taught education in Com...,Contributors 130,[]
22,[karpathy/nn-zero-to-hero],[Neural Networks: Zero to Hero],Contributors 2,"[Jupyter Notebook, 100.0%]"
23,[ggerganov/whisper.cpp],[Port of OpenAI's Whisper model in C/C++],Contributors 44,"[C, 52.6%, C++, 29.2%, Go, 8.8%, Python, 3.0%,..."
24,[btcpayserver/btcpayserver],"[Accept Bitcoin payments. Free, open-source & ...",Contributors 141,"[C#, 70.4%, HTML, 17.4%, CSS, 8.8%, JavaScript..."

# Q6. Scrape the details of top 100 songs on billboard.com

In [203]:
# Connecting to the driver
driver = webdriver.Chrome(r"C:\Users\navee\Downloads\chromedriver_win32\chromedriver.exe")
time.sleep(2)


# Opening webpage

driver.get("https://www.billboard.com/")
time.sleep(10)

search1 = driver.find_element(By.XPATH,'//*[@id="main-wrapper"]/header/div/div[2]/div/div/div[1]/div[1]/button')
search1.click()
time.sleep(3)

search1 = driver.find_element(By.XPATH,'//*[@id="main-wrapper"]/div[9]/div/div/div/ul/li[1]/ul/li[2]/a')
search1.click()
time.sleep(12)


# Scraping Billboard Hot 100

bill =[]
bi = driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]')
for i in bi:
    bill.append(i.text)

# Scraping song name

song = []
for i in range(len(bill)):
    if i==len(bill)-101:
        break
    else:
        son = bill[i].strip().split(",")[0].strip().split("\n")[0]
    song.append(son)
    
    
# Scraping Artist

artist = []
for i in range(len(bill)):
    if i==len(bill)-101:
        break
    else:
        art = bill[i].strip().split("\n")[1]
    artist.append(art)
    
# Scraping last week rank

lwr = []
for i in range(len(bill)):
    if i==len(bill)-101:
        break
    else:
        lr = bill[i].strip().split("\n")[2]
    lwr.append(lr)
    

# Scraping Peak Rank

pkr = []
for i in range(len(bill)):
    if i==len(bill)-101:
        break
    else:
        pk = bill[i].strip().split("\n")[3]
    pkr.append(pk)
    
    
# Scraping Peak Rank

wb = []
for i in range(len(bill)):
    if i==len(bill)-101:
        break
    else:
        w = bill[i].strip().split("\n")[4]
    wb.append(w)

In [204]:
# Creating DataFrame

Billboard_top_100 = pd.DataFrame({"Song Name":song,"Artist":artist,"Last Week Rank":lwr,"Peak Rank":pkr,
                                  "Weeks on Board":wb})
Billboard_top_100

,Song Name,Artist,Last Week Rank,Peak Rank,Weeks on Board
0,Anti-Hero,Taylor Swift,1,1,12
1,Kill Bill,SZA,3,2,5
2,Unholy,Sam Smith & Kim Petras,2,1,16
3,I'm Good (Blue),David Guetta & Bebe Rexha,4,4,20
4,Creepin',"Metro Boomin, The Weeknd & 21 Savage",6,5,6
...,...,...,...,...,...
95,Ditto,NewJeans,-,96,1
96,That's What Tequila Does,Jason Aldean,-,97,1
97,Gone Girl,SZA,94,43,5
98,SOS,SZA,90,32,5
99,You Didn't,Brett Young,-,100,1

# Q7. Scrape the details of Data science recruiters from naukri.com

Question skipped as it has been excluded from assignment Ticket #13739

# Q8. Scrape the details of Highest selling novels

In [232]:
# Connecting to the driver
driver = webdriver.Chrome(r"C:\Users\navee\Downloads\chromedriver_win32\chromedriver.exe")
time.sleep(3)

# Opening web page
driver.get("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare")
time.sleep(5)


rank = []
book = []
author = []
volume = []
publish = []
genre = []


# scraping rank
rk = driver.find_elements(By.XPATH,'/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[1]')
for i in rk:
    rank.append(i.text)


# scraping book name
bk = driver.find_elements(By.XPATH,'/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[2]')
for i in bk:
    book.append(i.text)


# scraping author
at = driver.find_elements(By.XPATH,'/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[3]')
for i in at:
    author.append(i.text)


# scraping volume sold
vl = driver.find_elements(By.XPATH,'/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[4]')
for i in vl:
    volume.append(i.text)
 
    
# scraping publisher
pl = driver.find_elements(By.XPATH,'/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[5]')
for i in pl:
    publish.append(i.text)

    
# scraping genre
gr = driver.find_elements(By.XPATH,'/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[6]')
for i in gr:
    genre.append(i.text)


#Creating DataFrame

Best_Selling_Books = pd.DataFrame({"Rank":rank,"Book Name":book,"Author Name":author,"Volumes Sold":volume,
                                   "Publisher":publish,"Genre":genre})
                       
Best_Selling_Books

,Rank,Book Name,Author Name,Volumes Sold,Publisher,Genre
0,1,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,2,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,3,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,4,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,5,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...,...
95,96,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,97,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,98,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,99,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,100,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# Q9. Scrape the details most watched tv series of all time from imdb.com

In [238]:
# Connecting to the driver
driver = webdriver.Chrome(r"C:\Users\navee\Downloads\chromedriver_win32\chromedriver.exe")
time.sleep(3)

# Opening web page
driver.get("http://www.imdb.com/list/ls095964455/")
time.sleep(10)


title=[]
year=[]
genre=[]
runtime=[]
rating=[]
vote=[]

# Scraping title
tl = driver.find_elements(By.XPATH,'//*[@id="main"]/div/div[3]/div[3]/div/div[2]/h3/a')
for i in tl:
    title.append(i.text)
    
    
# Scraping Year span 
yr = driver.find_elements(By.XPATH,'//span[@class="lister-item-year text-muted unbold"]')
for i in yr:
    year.append(i.text)
    
    
# Scraping genre
gr = driver.find_elements(By.XPATH,'//span[@class="genre"]')
for i in gr:
    genre.append(i.text)

    
# Scraping runtime
rn = driver.find_elements(By.XPATH,'//span[@class="runtime"]')
for i in rn:
    runtime.append(i.text)
    
# Scraping ratings
rt = driver.find_elements(By.XPATH,'//*[@id="main"]/div/div[3]/div[3]/div/div[2]/div[1]/div[1]/span[2]')
for i in rt:
    rating.append(i.text)
    

# Scraping votes
vt = driver.find_elements(By.XPATH,'//span[@name="nv"]')
for i in vt:
    vote.append(i.text)
    

# Creating DataFrame

Tv_series_Most_Watched = pd.DataFrame({"Title":title,"Year":year,"Genre":genre,"Runtime":runtime,
                             "Ratings":rating,"Votes":vote})
Tv_series_Most_Watched

,Title,Year,Genre,Runtime,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,109,986"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"1,200,307"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"999,591"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"295,684"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"254,553"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.4,"50,534"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"62,338"
97,Criminal Minds,(2005– ),"Crime, Drama, Mystery",42 min,8.1,"201,283"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"41,870"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"248,783"

# Q10. Details of Datasets from UCI machine learning repositories

In [260]:
# Connecting to the driver
driver = webdriver.Chrome(r"C:\Users\navee\Downloads\chromedriver_win32\chromedriver.exe")
time.sleep(3)

# Opening web page
driver.get("https://archive.ics.uci.edu/")
time.sleep(8)

search1 = driver.find_element(By.XPATH,'/html/body/table[1]/tbody/tr/td[2]/span[2]/a')
search1.click()


dtname=[]
dtset=[]
dtask=[]
attribute=[]
instance=[]
attn = []
year = []

# Scraping Dataset name
dt = driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b/a')
for i in dt:
    dtname.append(i.text)

# Scraping Dataset Type  
dts = driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]/p')
for i in dts:
    dtset.append(i.text)
    

# Scraping Task
dtk = driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]/p')
for i in dtk:
    dtask.append(i.text)
    

# Scraping Attribute Type
at = driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]/p')
for i in at:
    attribute.append(i.text)

    
# Scraping No of Instances
ins = driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]/p')
for i in ins:
    instance.append(i.text)

    
# Scraping No of Attributes
atn = driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]/p')
for i in atn:
    attn.append(i.text)
    

# Scraping year
yr = driver.find_elements(By.XPATH,'/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]/p')
for i in yr:
    year.append(i.text)
    
    
# Creating Dataframe

Datasets_UCI = pd.DataFrame({"Dataset Name":dtname,"Data Type":dtset[1:623],"Task":dtask[1:623],
                            "Attribute Type":attribute[1:623],"No of Instances":instance[1:623],
                            "No of Attribute":attn[1:623],"Year":year[1:623]})
Datasets_UCI

,Dataset Name,Data Type,Task,Attribute Type,No of Instances,No of Attribute,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,,Classification,,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021